CREATE USER IF NOT EXISTS 'xat_user'@'localhost' IDENTIFIED WITH mysql_native_password BY '123456';
GRANT USAGE ON *.* TO 'xat_user'@'localhost';
ALTER USER 'xat_user'@'localhost' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON xat_app.* TO 'xat_user'@'localhost';
FLUSH PRIVILEGES;
